### ISSUE TITLE
Manage pqGrid in percentage 

### ISSUE THREAD

**Issue by ketanpawar** [paramquery/grid#117]
Hello Everyone ,

**Comment by ketanpawar** [comment]
Hello Everyone ,  
I am working on pqGrid and I want to manage width of grid in percentage . I tried that on pqGrid demo but not able to manage grids .
Can anyone help me for this .
Thank you .

**Comment by isdh** [comment]
Hi @ketanpawar 

You can manage grid's width in percentage by String,  Not Number.
I confirm that by Chrome 52.  Please try it :smiley: 

```js

        var obj = {
            width: "10%",
            height: 400,
        ...

```
