### ISSUE TITLE
Hide() of the grid's DIV,  refreshView and then show(): missing content

### ISSUE THREAD

**Issue by meliezer** [paramquery/grid#119]
Hello,
As you can see in [http://jsfiddle.net/937futh9/](url) I've simply added three lines for demonstrating the problem:
        $("#grid_json").hide();
        $("#grid_json").pqGrid( "refreshView" );
        $("#grid_json").show();
Work-around: collapse and then re-expand the grid.
I don't use anymore destroy for the old object as in the missing headers problem reported at http://paramquery.com/forum/index.php?topic=1713.msg7183#msg7183
, but maybe also here the problem is related to the element hiding.

Best regards,
Menashè

**Comment by paramquery** [comment]
grid can be refreshed only after show()

$("#grid_json").hide();
$("#grid_json").show();
$("#grid_json").pqGrid( "refreshView" ); //only refresh would also do.

http://jsfiddle.net/937futh9/1/

**Comment by meliezer** [comment]
Thank you for the prompt reply! I confirm it works.
I simply wanted to keep the grid hidden during the refresh, but show() right before the refresh is good enough. 
(I've added in my original post 'Work-around in the code' just for having a complete post.
