### ISSUE TITLE
Export to excel not working

### ISSUE THREAD

**Issue by vsagar100** [paramquery/grid#123]
Hi, I am trying to export excel data to excel but when clicking on Export button it is giving error SCRIPT257: Could not complete the operation due to error 80020101. 
I am pulling data using custom logic & assignint it to grid. Data is appearing fine only export is not working.
Also confirm, the url param should the one where data will be posted temporary or what is its significance.

var data1 = getData();
 var obj = { width: 700, height: 400, title: "ParamQuery Grid Example",resizable:false,draggable:false, editable : false,
	  groupModel:{                
                dataIndx: ["Status","App"],                
                collapsed: [ true, true],
                title: ["<b style='font-weight:bold;'>{0} ({1} orders)</b>","{0} - {1}"], 
                dir: ["up","down"]
                //,icon: ["circle-plus", "circle-triangle", "triangle"]
            },
	 pageModel: {type:'local'},
	  toolbar: {
                cls: 'pq-toolbar-export',
                items: [{
                        type: 'button',
                        label: "Export to Excel",
                        icon: 'ui-icon-document',
                        listeners: [{
                            "click": function (evt) {
                                $("#data-table").pqGrid("exportExcel", { url: "https://mysite.com/repository/", sheetName: "pqGrid sheet" });
                            }
                        }]
                }]
            }
		}
        obj.colModel = [{ title: "Status", width: 100, dataIndx: "Status", dataType: "string" },
        { title: "App", width: 200, dataIndx: "App", dataType: "string" },
        { title: "Count", width: 150, dataIndx: "Count", dataType: "integer", align: "right" }];
        obj.dataModel = { data : data1, location : "local" }; 
	
        $("#data-table").pqGrid(obj);

**Comment by paramquery** [comment]
Exported data is posted to url param 

Local export is also available in v3.5 to avoid round trip to server

https://paramquery.com/demos/export_local
