### ISSUE TITLE
Cooperation with ReactJS

### ISSUE THREAD

**Issue by Kermel** [paramquery/grid#129]
Hi, I would like to ask if there is a plan to make this library work with ReactJS framework in the near future?

Thanks

Ondrej

**Comment by paramquery** [comment]
Yes, there is a plan to make it work with ReactJS.

**Comment by xingmolu** [comment]
How will the react when released?

**Comment by paramquery** [comment]
Please check these examples for ReactJS support

https://paramquery.com/demos/react_method
https://paramquery.com/demos/react_event
