### ISSUE TITLE
Drop down list on cell assume label = value and empty current list choice on editing [Work Around]

### ISSUE THREAD

**Issue by AbdelrahmanAli** [paramquery/grid#139]
So I created a pqgrid with edit button. I use an editor for one of the columns in my grid.

The editor create a drop down menu. The initial values of the drop down menu are set using an array of value-label pairs. So that, the drop down menu shows the labels, but sends the value when contacting the server.

When I press the edit button, the label of the cell becomes NULL and it ruin the current value. After investigation, I found that when I go to edit mode, it treat the label as if it is the value. 

For example if I have label = 'IPP' and value = 'IPP'
and I press edit, it works fine and shows me IPP in the list as current value.

![3](https://user-images.githubusercontent.com/9371556/28619078-70f48ad2-720f-11e7-90c6-4e46c804199c.PNG)

On the other hand, if I have label = 'Bank Trade' and value = 'BT'
and I press edit, it doesn't work. It make the current label EMPTY, or NULL. 
![1](https://user-images.githubusercontent.com/9371556/28619089-78a4de3a-720f-11e7-93aa-7717cd613250.PNG)

![2](https://user-images.githubusercontent.com/9371556/28619092-7d182dfa-720f-11e7-97f5-9d7160e45b43.PNG)

Snippets from the code:

        colModel: [
                    { title: "Id", dataType: "string", dataIndx: "id", editable:false, width: 80},
                     { title: "Channel", dataType: "string", dataIndx: "channel", width: 80, 
                        editor: {type:'select',
                        init: function(ui,evet){ }
                        ,options: channels_selector},
                        validations: [{ type: 'nonEmpty', msg: "Required" } ] }

The **channels_selector** array is an array of associative label, value pairs [ {value1: label1}, {value2: label2},..].

**So as a conclusion, the pqgrid assume that the VALUE is the same thing as the LABEL. This behavior is not correct.**

_Work around to solve this issue:_

                       init: function(ui,evet){ 
                                var found = false;
                                var arrayLength = channels_selector.length;
                                for (var i = 0; i < arrayLength && !found; i++) {
                                    var p = channels_selector[i];
                                    for (var key in p) {
                                      if (p.hasOwnProperty(key) && p[key]==ui['cellData']) {
                                            ui.$cell.find("select")[0].value = key;
                                            found = true;
                                            break;                                            
                                      }
                                    }
                                }
                            }

**In the work around, I assume the relation between the value label and label value are 1 to 1**

**Comment by paramquery** [comment]
Please check this example: https://paramquery.com/demos/editing_custom. value label pairs are used in ShipVia column and work fine.

Please share a jsfiddle if you face any issue with that.
