### ISSUE TITLE
Not able to use the plugin

### ISSUE THREAD

**Issue by A-ravi-nd** [paramquery/grid#146]
The browser is throwing the following exception -
"pqgrid.min.js:1 Uncaught TypeError: n.widget is not a function
    at pqgrid.min.js:1
    at pqgrid.js:282"

Can you please let me know how to fix this and integrate the plugin into my application?

Thank you.

**Comment by paramquery** [comment]
From your description, it seems you haven't included jqueryui.

Dependencies should be included in this order.
jQuery
jQueryui
pqgrid

**Comment by A-ravi-nd** [comment]
Thank you. 
Able to use the plugin now

But facing a new issue with the grid.
- Not able to update any records on the grid.
-Add and deleting of records is working fine.
-The isdirty() method is not recognising an update and hence changes() does not contain the changes.updatelist.
-Please let me know what might be the issue and help me resolve.
Thanks in advance.
