### ISSUE TITLE
Update functionality on the grid is not working

### ISSUE THREAD

**Issue by A-ravi-nd** [paramquery/grid#148]
- Not able to update any records on the grid.
-Adding and deleting of records is working fine.
-The isdirty() method is not recognising an update and hence changes() does not contain the changes.updatelist.
-Please let me know what might be the issue and help me resolve.
Thanks in advance.

**Comment by paramquery** [comment]
Have you enabled tracking and specified primary key dataModel.recIndx

**Comment by A-ravi-nd** [comment]
It is working now. Thank you.
