### ISSUE TITLE
Uncaught dataIndx NA

### ISSUE THREAD

**Issue by w3lifer** [paramquery/grid#151]
Click on the select: https://jsfiddle.net/12kehav8

**Comment by CheolHoJung** [comment]
Why use SumoSelect? how about using pqselect?
https://jsfiddle.net/12kehav8/28/

**Comment by w3lifer** [comment]
@CheolHoJung, this is a requirement.

**Comment by CheolHoJung** [comment]
Take a look at console.
```javascript
pqgrid.dev.js:4052 Uncaught dataIndx NA
fn.getColIndx @ pqgrid.dev.js:4052
(anonymous) @ jquery-ui.js:144
_pMouseSelection.scrollColumnNonVirtual @ pqgrid.dev.js:15036
fn.scrollColumn @ pqgrid.dev.js:4570
(anonymous) @ jquery-ui.js:144
handleFocus @ pqgrid.dev.js:9865
dispatch @ jquery.js:5183
elemData.handle @ jquery.js:4991
trigger @ jquery.js:8249
simulate @ jquery.js:8318
handler @ jquery.js:8352
trigger @ jquery.js:5306
trigger @ jquery.js:8214
(anonymous) @ jquery.js:8327
each @ jquery.js:354
each @ jquery.js:189
trigger @ jquery.js:8326
jQuery.fn.(anonymous function) @ jquery.js:10212
showOpts @ jquery.sumoselect.js:287
(anonymous) @ jquery.sumoselect.js:382
dispatch @ jquery.js:5183
elemData.handle @ jquery.js:4991
```

When you click for SumoSelect, trigger select.focus. See handleFocus @ pqgrid.dev.js:9865.

```javascript
var $target = $(e.target),
  $inp = $target.closest(".pq-grid-hd-search-field"),
  dataIndx = $inp.attr("name");
```

_pHeaderSearch._bindFocus function finds dataIndx from $target.closest(".pq-grid-hd-search-field"). **If no use Sumoselect, $target is select tag. But, if use it $target is div tag that is parent of select tag.**

Therefore, if you should use SumoSelect, you should extend or edit _pHeaderSearch._bindFocus.
