### ISSUE TITLE
How to bind json to grid

### ISSUE THREAD

**Issue by jstzwhc** [paramquery/grid#153]
JSON data:
{
"totalRecords":1,"curPage":1,"data":[
{"OperationLogID":1,"Corporation":{"CorporationID":2,"ParentID":1,"BusinessName":"abc","CreationDate":"2018-01-09 10:32:56.000","UpdatedDate":null,"Uploaded":false,"IsDeleted":false},
"Department":{"DepartmentID":37,"CorporationID":2,"ParentID":33,"Deptname":"def","CreationDate":"2018-01-24 12:35:50.000","UpdatedDate":null,"Uploaded":false,"IsDeleted":true},
"User":{"UserID":1,"CorporationID":2,"DepartmentID":37,"RoleID":1,"LoginName":"admin","UserName":"admin","Password":"admin","CreationDate":"2018-04-13 12:21:30.227","UpdatedDate":null,"Uploaded":false,"IsDeleted":false},
"Method":"add","Contents":"gh","CreationDate":"2018-04-13 10:15:22.317","UpdatedDate":null,"Uploaded":false,"IsDeleted":false}]}
**How to bind** 
{ title: "Company", width: 150, dataType: "string", align: "center", dataIndx: "Corporation.BusinessName" }
**but in grid is blank.**

**Comment by paramquery** [comment]
https://paramquery.com/demos/grid_json
