### ISSUE TITLE
AngularJS: Plugin not working

### ISSUE THREAD

**Issue by dxyphr** [paramquery/grid#159]
I am unable to use the angularjs version of the plugin. 
the browser keeps throwing:

> angular.js:15018 TypeError: Cannot read property 'ngModel' of undefined
    at new cGrid (ng.pqgrid.js:55)
    at Object.link (ng.pqgrid.js:398)

will be glad if you can help me resolve this ASAP.

**Comment by paramquery** [comment]
It works fine in the examples. Please share a jsiddle/ plnkr so that your code can be checked.
