### ISSUE TITLE
DeleteRows is buggy

### ISSUE THREAD

**Issue by lechurn** [paramquery/grid#173]
```
var rowIndxToRemoved = [3,4,5]; // example of rowIndx to delete
 if (rowIndxToRemoved.length > 0) {
     rowIndxToRemoved.forEach(function (item) {
         $('#grid_json').pqGrid("deleteRow", {
             rowIndx: item, effect: true, source:'delete' ,complete: function () {
                 $grid.pqGrid("removeClass", { rowIndx: item, cls: 'pq-row-delete' });
             }
         });
     });
 }

```
The above sample code of me deleting rows. Assuming that I have 6 rows of data in the grid. 
Once "deleteRow" is ran once, 
a) grid with rowIndx "3" will be deleted, 
b) position of grid with rowIndx "4" will be taken by grid with previously rowIndx "5".
c) position of grid with rowIndx "3" will be taken by grid with previously rowIndx "4".

Numbers represent the previous rowIndx replacing the current rowIndx
Before First Delete Row
1
2
3
4
5
6

> 

1st Delete Row  (delete with rowIndx "3")
1
2
4 (now using rowIndx 3)
5 (now using rowIndx 4)
6 (now using rowIndx 5)

2nd Delete Row (delete with rowIndx "4")
1
2
4 (now using rowIndx 3)
6 (now using rowIndx 5)

3rd Delete Row (delete with rowIndx "5")
1
2
4 (now using rowIndx 3)

> 

Expected Result should be

> 
1st Delete Row  (delete with rowIndx "3")
1
2
4 (now using rowIndx 4)
5 (now using rowIndx 5)
6 (now using rowIndx 6)

2nd Delete Row (delete with rowIndx "4")
1
2
5 (now using rowIndx 5)
6 (now using rowIndx 6)

3rd Delete Row (delete with rowIndx "5")
1
2
6 (now using rowIndx 3)

>
The end result is left row 1 , 2 and 6 only. 

When I delete, it should be deleted rowIndx 3, 4 , 5 together. 
I've also tried deleting rowList with all the rowIndx 3, 4, 5 the result is same as code above.

**Comment by lechurn** [comment]
One of the solution is use DeleteNodes instead.
First get the rowData of the row that you wished to delete.
store the rowData into an array. 
eg 
`  var` rowDataz = [];
    rowDataz.add(rowData);
   
   $('#grid_data').pqGrid("deleteNodes", rowDataz);
`

**Comment by paramquery** [comment]
deleteNodes method is available in Pro only

For free version (https://paramquery.com/api#method-deleteRow), 
use
rowIndxToRemoved = rowIndxToRemoved.sort().reverse();
