### ISSUE TITLE
Getting error in the pqgrid.min.js and pqgrid.dev.js file

### ISSUE THREAD

**Issue by Fareedbaba** [paramquery/grid#174]
Hello Param,

i am getting the following error while loading the pggrid.dev.js file from the shared code base
Uncaught TypeError: $.widget is not a function

i have followed the same order for loading the files, yet the issue.
Can you please specify if am missing any dependency here.

Thanks a lot in advance. your inputs will be very helpful.

**Comment by paramquery** [comment]
Please ensure to include the jqueryui library. If already added then check correctness of its path. Look out for any 404 errors in the browser console.

**Comment by Fareedbaba** [comment]
Thanks for your response Param,
I was able to solve the issue by adding the appropriate references
