### ISSUE TITLE
How to resize the column upto we want 

### ISSUE THREAD

**Issue by Kranthi32** [paramquery/grid#184]
Hi Team,
Thanks for you effort and work. How to resize the column up to we want and how to check column resize event please provide an example.

**Comment by paramquery** [comment]
column can be resized by dragging the edge of column in header UI and columnResize event can be used to detect the resize.

https://paramquery.com/api#event-columnResize

**Comment by Kranthi32** [comment]
Hi Thanks for the reply, my column is moving upto 1237px after that it is not expanding. but i want more. how to extend It.

![image](https://github.com/paramquery/grid/assets/99165841/76e25f41-703f-42f9-b9d0-dac5688f7a52)

**Comment by Kranthi32** [comment]
any solution to resize upto we want

**Comment by paramquery** [comment]
you can increase the maximum width of column with help of column,maxWidth option.

https://paramquery.com/api#option-column-maxWidth

**Comment by Kranthi32** [comment]
Hi, In below demo for first column i set maxWidth is 2000 but it is not setting.

https://paramquery.com/demos241

obj.colModel = [{ title: "Rank", maxWidth: 2000, dataType: "integer", dataIndx: "rank" },
            { title: "Company", width: 220, dataType: "string", dataIndx: "company" },
            { title: "Revenues ($ millions)", width: 180, dataType: "float", align: "right", dataIndx: "revenues" },
            { title: "Profits ($ millions)", width: 150, dataType: "float", align: "right", dataIndx: "profits" }
        ];

**Comment by Kranthi32** [comment]
Any solution on this.

**Comment by paramquery** [comment]
Note that maxWidth allows to set or resize the column upto that value.

It's working fine for me in this example: https://paramquery.com/demos241/freeze_columns

please share a jsfiddle if you  are facing issue

**Comment by Kranthi32** [comment]
Thanks for your Replay, as per your shared demo , i can expand the column up to 1122 px, after this its not moving. if i want expand more than this how can i expand. please find below  image after reaching this size its not moving more .

![image](https://github.com/paramquery/grid/assets/99165841/4f04d917-6021-461e-a02c-0446e4bd3948)
 changed code in demo is 


    $(function () {
        var columns = [
            { title: "Order ID", width: 100, dataIndx: "OrderID" },
            { title: "Customer Name", width: 130, dataIndx: "CustomerName" },
            { title: "Product Name", width: 140, dataIndx: "ProductName" },
            { title: "Unit Price", width: 100, dataIndx: "UnitPrice", align: "right" },
            { title: "Quantity", width: 100, dataIndx: "Quantity", align: "right" },
		    { title: "Order Date", width: 100, dataIndx: "OrderDate" },
		    { title: "Required Date", width: 100, dataIndx: "RequiredDate" },
		    { title: "Shipped Date", width: 100, dataIndx: "ShippedDate" },
            { title: "ShipCountry", width: 100, dataIndx: "ShipCountry" },
            { title: "Freight", width: 100, align: "right", dataIndx: "Freight" },
            { title: "Shipping Name", width: 120, dataIndx: "ShipName" },
            { title: "Shipping Address", width: 180, dataIndx: "ShipAddress" },
            { title: "Shipping City", width: 100, dataIndx: "ShipCity" },
            { title: "Shipping Region", width: 110, dataIndx: "ShipRegion" },
            { title: "Shipping Postal Code", width: 160, dataIndx: "ShipPostalCode", minWidth: 150 }
		];
        var dataModel = {
            location: "remote",
            sorting: "local",
            dataType: "JSON",
            method: "GET",
            url: "/Content/invoice.json",
            getData: function (dataJSON) {
                var data = dataJSON.data;
                var rowdata = data[4];
                rowdata.pq_cellattr = {
                    CustomerName: { colspan: 2, style: "text-align:center;background:green;color:#fff;" },
                    ProductName: { style: "display:none;" }
                };
                rowdata.CustomerName = "I am merged cell. Check how I work when frozen in the middle.";
                return { curPage: dataJSON.curPage, totalRecords: dataJSON.totalRecords, data: data };
            }
        }

        var $grid = $("div#grid_freeze_columns").pqGrid({
            height: 500,            
            dataModel: dataModel,
            dragColumns: {enabled: false},
            pageModel: { type: 'local', rPP: 20, rPPOptions: [1, 10, 20, 30, 40, 50, 100] },
            colModel: columns,
            selectionModel: {type: 'row'},
			columnResize: function (event, ui) {
                var column = ui.column;
                var extrawidth="";

                var gridWidth = $grid.width(); // Get the width of the grid container
				console.log(gridWidth);
				console.log(column.width)
                // Apply the maximum width threshold if needed
                
                return true;
            },
            toolbar: {
                style: "text-align:center",
                items: [
                    { type: '<span>Number of frozen columns: </span>' },
                    { type: 'select', options: [0, 1, 2, 3], listeners: [
                        {
                            change: function (evt) {
                                $grid.pqGrid("option", "freezeCols", $(this).val());
                                $grid.pqGrid("refresh");
                            }
                        }
                    ]
                    },
                    { type: 'separator' },
                    { type: 'checkbox', style: 'margin-right:5px;', attr: 'id=wrapText checked="checked"', listeners: [
                        {
                            change: function (evt) {
                                if ($(this).is(":checked")) {
                                    $grid.pqGrid("option", { wrap: true, hwrap: true });
                                }
                                else {
                                    $grid.pqGrid("option", { wrap: false, hwrap: false });
                                }
                                $grid.pqGrid("refresh");
                            }
                        }
                    ]
                    },
                    { type: "<label for='wrapText'>Wrap Text</label>" }
                ]
            },
            numberCell: { resizable: true, width: 40, title: "#", minWidth: 25 },
            title: "Shipping Orders",
            resizable: true
        });
    });

**Comment by Kranthi32** [comment]
Thanks for the support its working
