### ISSUE TITLE
Get filtred data

### ISSUE THREAD

**Issue by belhauss** [paramquery/grid#90]
Hello,

Thanks for this awesome plugin !

How can I get the filtered DATA in an array ? like you do in the exportCsv and exportExcel I wanna generate a PDF using this data.

I tried the methods on the API but none could achieve this.

Thanks

**Comment by paramquery** [comment]
It's simple.

dataModel.data always points to current data in grid (filtered or unfiltered).

var data = grid.option( 'dataModel.data' );

**Comment by belhauss** [comment]
Ohh thanks man.
